#!/bin/sh
# chkconfig: 345 99 10
# description: Auto-starts tomcat
# /etc/init.d/tomcatd
# Tomcat auto-start
# Source function library.
#. /etc/init.d/functions
# source networking configuration.
#. /etc/sysconfig/network
RETVAL=0

#set java environment
export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
export JRE_HOME=${JAVA_HOME}/jre
export CLASSPATH=.:%{JAVA_HOME}/lib:%{JRE_HOME}/lib
export PATH=${JAVA_HOME}/bin:$PATH

#tomcat
export TOMCAT_HOME=/opt/apache-tomcat-9.0.40
export CATALINA_HOME=${TOMCAT_HOME}
export CATALINA_BASE=${TOMCAT_HOME}

start()
{
	if [ -f $CATALINA_HOME/bin/startup.sh ];then
		echo "Starting Tomcat"
		$CATALINA_HOME/bin/startup.sh
		RETVAL=$?
		echo " OK"
		return $RETVAL
	fi
}
stop()
{
	if [ -f $CATALINA_HOME/bin/shutdown.sh ];then
		echo "Stopping Tomcat"
		$CATALINA_HOME/bin/shutdown.sh
		RETVAL=$?
		sleep 1
		ps -fwwu root | grep tomcat|grep -v grep | grep -v PID | awk '{print $2}'|xargs kill -9
		echo " OK"
		# [ $RETVAL -eq 0 ] && rm -f /var/lock/...
		return $RETVAL
	fi
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;

	restart)
		echo "Restaring Tomcat"
		$0 stop
		sleep 1
		$0 start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac
exit $RETVAL
