""""""""""""""""""""""""""""""""""""""""""""""""""
" 显示相关
""""""""""""""""""""""""""""""""""""""""""""""""""

" 配置变更立即生效
autocmd BufWritePost $MYVIMRC source $MYVIMRC

"设置编码
set fileencodings=utf-8,ucs-bom,gb18030,gbk,gb2312,cp936,cp936,big5,euc-jp,euc-kr,latin1 
set termencoding=utf-8
set encoding=utf-8

" 检测文件类型
filetype on
" 针对不同的文件类型，采用不同的缩进方式
filetype indent on
" 针对不同的文件类型，加载对应的插件
filetype plugin on
" 启动自动补全
filetype plugin indent on
" 文件修改之后自动读入
set autoread
" 开启语法高亮
syntax enable
" 开启语法高亮
syntax on 

"显示行号
set number		"set nu

"突出显示当前行
set cursorline		"set cul
"突出显示当前列
"set cuesorcolumn	"set cuc
"显示光标所在的当前行的行号，其他行都为相对于该行的相对行号。
"set relativenumber

"启用鼠标
"set mouse=a
"set selection=exclusive
"set selectmode=mouse,key

"设置缩进
"set tabstop=4		"设置Tab长度为4空格
"set shiftwidth=4	"设置自动缩进长度为4空格
set autoindent		"继承前一行的缩进方式，适用于多行注释
" 设置C/C++方式自动对齐
set cindent
set smartindent

"不将Tab转换为空格
set noexpandtab
" 在行和段开始处使用制表符
set smarttab
"不在单词中间进行折行
set lbr

"设置粘贴模式
set paste

"显示状态栏和光标当前位置
set laststatus=2 	"总是显示状态栏
set ruler		"显示光标当前位置
" 状态栏
set statusline=%<%f\ %h%m%r%=%k[%{(&fenc==\"\")?&enc:&fenc}%{(&bomb?\",BOM\":\"\")}]\ %-14.(%l,%c%V%)\ %P
" 在状态栏显示正在输入的命令
set showcmd
" 左下角显示当前vim模式
set showmode
" 不与vi兼容(采用vim自己的操作命令)
set nocompatible
"启动256色
set t_Co=256

"""搜索
"显示括号匹配
set showmatch
"高亮显示匹配结果
set hlsearch
"输入搜索模式时，每输入一个字符，就自动跳到第一个匹配的结果。
set incsearch
"搜索时忽略大小写
set ignorecase
""如果同时打开了ignorecase，
"那么对于只有一个大写字母的搜索词，
"将大小写敏感；其他情况都是大小写不敏感。
"比如，搜索Test时，将不匹配test；搜索test时，将匹配Test
set smartcase

""设置备份文件、交换文件、操作历史文件的保存位置
"结尾的//表示生成的文件名带有绝对路径，路径中用%替换目录分隔符，这样可以防止文件重名
"set backupdir=~/.vim/.backup//  
"set directory=~/.vim/.swp//
"set undodir=~/.vim/.undo// 

"自动切换目录
set autochdir

"底部命令自动补全
set wildmenu
set wildmode=longest:list,full

" 设置历史记录条数
"set history=65535

setlocal list
set listchars=tab:>-,trail:-

highlight MyTabSpace guifg=darkgrey ctermfg=darkgrey
match MyTabSpace /\t\| /

map <F2> :setlocal list<cr>
map <F2><F2> :setlocal nolist<cr>

"" 原格式复制内容：
:set pastetoggle=<F9> "等效上面两行内容
		
map <F4> :g/^\s+$/d<cr>
